const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
function fixture(storage=new Map(),fetchImpl=()=>Promise.reject(Error('offline')),includeStageOne=false){
  const elements=new Map();
  function makeElement(id){let html='',queries=new Map();return {id,attributes:{},setAttribute(name,value){this.attributes[name]=value;},value:'',checked:false,textContent:'',style:{},disabled:false,dataset:{},classList:{add(){},remove(){},toggle(){}},get innerHTML(){return html;},set innerHTML(value){html=value;queries=new Map();for(const match of value.matchAll(/<[^>]*\bid="([^"]+)"[^>]*>/g)){const child=makeElement(match[1]);child.value=match[0].match(/\bvalue="([^"]*)"/)?.[1]||'';child.checked=/\schecked(?:\s|>)/.test(match[0]);elements.set(child.id,child);}},querySelectorAll(selector){if(selector==='[data-study-word]')return [...html.matchAll(/data-study-word="([^"]+)"/g)].map(match=>({dataset:{studyWord:match[1]}}));if(selector==='.pick-options input:checked')return this.querySelectorAll('.pick-options input').filter(input=>input.checked);if(queries.has(selector))return queries.get(selector);let result=[];if(selector==='[data-count]'||selector==='[data-category]'){const attribute=selector.slice(1,-1),key=attribute==='data-count'?'count':'category';result=[...html.matchAll(new RegExp(attribute+'="([^"]+)"','g'))].map(match=>{const input=makeElement('');input.dataset[key]=match[1];return input;});}if(selector==='.pick-options input')result=[...html.matchAll(/<input type="checkbox" value="([^"]+)"([^>]*)>/g)].map(match=>{const input=makeElement('');input.value=match[1];input.checked=match[2].includes('checked');return input;});queries.set(selector,result);return result;}};}
  function element(id){if(!elements.has(id))elements.set(id,makeElement(id));return elements.get(id);}
  const context=vm.createContext({console,URL,AbortController,fetch:fetchImpl,setTimeout,clearTimeout,window:{},document:{getElementById:element,querySelector:element,activeElement:{tagName:'BODY'},addEventListener(){}},localStorage:{getItem:key=>storage.get(key)||null,setItem:(key,value)=>storage.set(key,value)}});
  const run=code=>vm.runInContext(code,context);
  for(const file of ['data.js',...(includeStageOne?['stage1-data.js','stage2-data.js','stage3-data.js']:[]),'search.js','app.js'])run(fs.readFileSync(require('node:path').join(__dirname,'../dist',file),'utf8'));
  return {run,element,storage};
}
module.exports={fixture};
